timeout: 3600s
options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY
  machineType: 'N1_HIGHCPU_8'

steps:
  # Build API Service (We use the same image for worker)
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-api-service'
    env:
      - 'DOCKER_BUILDKIT=1'
    args: [
      'build',
      '--memory=8g',
      '--cpu-quota=400000',
      '--build-arg', 'BUILDKIT_INLINE_CACHE=1',
      '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/api-service:$COMMIT_SHA',
      '-f', './apps/api/Dockerfile.deploy',
      './apps/api'
    ]

  # Push API Service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-api-service'
    args: [
      'push',
      '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/api-service:$COMMIT_SHA'
    ]
    waitFor: ['build-api-service']

  # Deploy Worker Service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy worker-service \
          --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPO_NAME}/api-service:$COMMIT_SHA \
          --region=${_REGION} \
          --platform=managed \
          --vpc-connector=crawlweb-connector \
          --port=8080 \
          --command="node" \
          --args="dist/src/services/cloud-run-worker.js" \
          --set-env-vars="REDIS_URL=redis://${_REDIS_IP}:6379,REDIS_RATE_LIMIT_URL=redis://${_REDIS_IP}:6379,REDIS_HOST=${_REDIS_IP},PLAYWRIGHT_MICROSERVICE_URL=${_PLAYWRIGHT_URL}/scrape,HOST=0.0.0.0,TEST_API_KEY=a01ccae" \
          --set-secrets="SUPABASE_URL=SUPABASE_URL:latest,SUPABASE_ANON_TOKEN=SUPABASE_ANON_TOKEN:latest,SUPABASE_SERVICE_TOKEN=SUPABASE_SERVICE_TOKEN:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest" \
          --memory=2Gi \
          --cpu=2 \
          --timeout=3600 \
          --no-allow-unauthenticated \
          --min-instances=1
    waitFor: ['push-api-service']

substitutions:
  _REGION: us-west2
  _REPO_NAME: crawlweb-repo
  _REDIS_IP: 10.110.96.2
  _PLAYWRIGHT_URL: https://playwright-service-475988465347.us-west2.run.app
